name: CheckFormat
on:
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"
      - name: Install
        run: |
          npm ci
      - name: CheckPrettier
        run: |
          npm run test:prettier
      - name: CheckJS
        run: |
          npm run test:js
      - name: CheckCSS
        run: |
          npm run test:css
