name: Format

on:
  push:
    branches: [master]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"
      - name: Install
        run: |
          npm ci
      - name: Prettier
        run: |
          npm run prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Apply formatting changes
          # GITHUB_TOKEN is never allowed to push changes to workflow files
          file_pattern: ". :!.github/workflows"
      - name: CheckJS
        run: |
          npm run test:js
      - name: CheckCSS
        run: |
          npm run test:css
